name: Main

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron:  '0 0 * * *'
  workflow_dispatch:
    
jobs:
  update-icons:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    # Install Rust
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2

    # Run the generator via `cargo`
    - name: Run Generator
      run: |
        cargo run --release --features=generator

    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: auto-update icons / pull submodules